#redisson node yml config
{
   "clusterServersConfig":{
      "nodeAddresses":[
         "//127.0.0.1:7004",
         "//127.0.0.1:7001",
         "//127.0.0.1:7000"
      ],
   },
   "threads":0,

   "executorServiceThreads": 0,
   "executorServiceWorkers": {"myExecutor1":3, "myExecutor2":5},
#   识别redisson client 端监听的分布式服务
   "redissonNodeInitializer": {"class":"org.mycompany.MyRedissonNodeInitializer"}
}